name: Setup Typsite
description: Install Typsite and add it to PATH using the appropriate package manager

branding:
  icon: terminal
  color: white

inputs:
  version:
    description: "Which version to install."
    required: false
    default: latest

outputs:
  version:
    description: "The installed Typsite version."

runs:
  using: node20
  main: dist/index.js
